"""initial schema

Revision ID: cf3e27b74779
Revises: 
Create Date: 2026-05-07 13:06:06.224296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf3e27b74779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('kategorie', sa.Enum('ITO', 'NON_ITO', 'EXTERN', name='departmentkategorie'), nullable=False),
    sa.Column('ansprechpartner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erlaubt_mehrfachbelegung', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_code'), ['code'], unique=True)

    op.create_table('schoolyear',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('start_kw', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_kw', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainee_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('berufsschule', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('unterrichts_typ', sa.Enum('BLOCK_FEST', 'ROTATIONS_BLOCK', 'DH_PHASEN', name='unterrichtstyp'), nullable=False),
    sa.Column('rotation_wochen_betrieb', sa.Integer(), nullable=True),
    sa.Column('rotation_wochen_schule', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainee_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainee_class_name'), ['name'], unique=True)

    op.create_table('school_holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolyear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('start_kw', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_kw', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schoolyear_id'], ['schoolyear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_holiday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_holiday_schoolyear_id'), ['schoolyear_id'], unique=False)

    op.create_table('school_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.Column('schoolyear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['klasse_id'], ['trainee_class.id'], ),
    sa.ForeignKeyConstraint(['schoolyear_id'], ['schoolyear.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('klasse_id', 'schoolyear_id', name='uq_plan_klasse_year')
    )
    with op.batch_alter_table('school_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_plan_klasse_id'), ['klasse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_plan_schoolyear_id'), ['schoolyear_id'], unique=False)

    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('nachname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=True),
    sa.Column('rolle', sa.Enum('AZUBI', 'DH_STUDENT', 'PRAKTIKANT', 'UMSCHUELER', name='traineerolle'), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('notizen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['klasse_id'], ['trainee_class.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainee_klasse_id'), ['klasse_id'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('schoolyear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kw', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('typ', sa.Enum('ABTEILUNG', 'URLAUB', 'BERUFSSCHULE', 'UNI', 'FREI', name='assignmenttyp'), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', name='assignmentsource'), nullable=False),
    sa.Column('notiz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['abteilung_id'], ['department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schoolyear_id'], ['schoolyear.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id', 'kw', 'jahr', name='uq_assign_trainee_kw_jahr')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index('ix_assign_year_kw_dept', ['schoolyear_id', 'kw', 'abteilung_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_schoolyear_id'), ['schoolyear_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_trainee_id'), ['trainee_id'], unique=False)

    op.create_table('school_plan_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kw', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('typ', sa.Enum('BERUFSSCHULE', 'UNI', name='schoolweektyp'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['school_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'kw', 'jahr', name='uq_planweek_plan_kw_jahr')
    )
    with op.batch_alter_table('school_plan_week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_plan_week_jahr'), ['jahr'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_plan_week_kw'), ['kw'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_plan_week_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_plan_week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_plan_week_plan_id'))
        batch_op.drop_index(batch_op.f('ix_school_plan_week_kw'))
        batch_op.drop_index(batch_op.f('ix_school_plan_week_jahr'))

    op.drop_table('school_plan_week')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_trainee_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_schoolyear_id'))
        batch_op.drop_index('ix_assign_year_kw_dept')

    op.drop_table('assignment')
    with op.batch_alter_table('trainee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainee_klasse_id'))

    op.drop_table('trainee')
    with op.batch_alter_table('school_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_plan_schoolyear_id'))
        batch_op.drop_index(batch_op.f('ix_school_plan_klasse_id'))

    op.drop_table('school_plan')
    with op.batch_alter_table('school_holiday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_holiday_schoolyear_id'))

    op.drop_table('school_holiday')
    with op.batch_alter_table('trainee_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainee_class_name'))

    op.drop_table('trainee_class')
    op.drop_table('schoolyear')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_code'))

    op.drop_table('department')
    # ### end Alembic commands ###
