"""drop rotations_block + rotation_wochen columns

Revision ID: f5db6557783c
Revises: cf3e27b74779
Create Date: 2026-05-08 14:31:23.636741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5db6557783c'
down_revision: Union[str, Sequence[str], None] = 'cf3e27b74779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Migrate any existing ROTATIONS_BLOCK rows to BLOCK_FEST so the enum
    # narrowing below cannot fail on legacy data.
    op.execute(
        "UPDATE trainee_class SET unterrichts_typ = 'BLOCK_FEST' "
        "WHERE unterrichts_typ = 'ROTATIONS_BLOCK'"
    )

    with op.batch_alter_table('trainee_class', schema=None) as batch_op:
        batch_op.alter_column('unterrichts_typ',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('BLOCK_FEST', 'DH_PHASEN', name='unterrichtstyp'),
               existing_nullable=False)
        batch_op.drop_column('rotation_wochen_schule')
        batch_op.drop_column('rotation_wochen_betrieb')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainee_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_wochen_betrieb', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rotation_wochen_schule', sa.INTEGER(), nullable=True))
        batch_op.alter_column('unterrichts_typ',
               existing_type=sa.Enum('BLOCK_FEST', 'DH_PHASEN', name='unterrichtstyp'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
