apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace: bei AI-Platform erfragen -> <<<NAMESPACE>>>
# Beispiel: wilbeth-test
namespace: <<<NAMESPACE>>>

resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.postgres.yaml
  - deployment.wilbeth.yaml
  - service.wilbeth.yaml
  - service.postgres.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: wilbeth
