apiVersion: v1
kind: Secret
metadata:
  name: wilbeth-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{dbPassword}}"
  DATABASE_URL: "postgresql+psycopg://wilbeth:{{dbPassword}}@postgres:5432/wilbeth"
  oidc-client-secret: "{{oidcClientSecret}}"
  session-secret: "{{sessionSecret}}"
